# Generated by Django 2.0.5 on 2018-08-15 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cebula', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='onoff',
            field=models.IntegerField(default=1),
        ),
    ]
