# Generated by Django 2.0.5 on 2018-08-15 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cebula', '0002_myuser_onoff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='onoff',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
