# Generated by Django 2.0.5 on 2018-09-26 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cebula', '0004_auto_20180817_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='category',
            field=models.ForeignKey(on_delete='CASCADE', related_name='Answer_category_name', to='cebula.Category'),
        ),
    ]
