# Generated by Django 2.0.5 on 2018-10-16 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cebula', '0006_auto_20181015_1420'),
    ]

    operations = [
        migrations.RenameField(
            model_name='share_answers',
            old_name='contents',
            new_name='answers',
        ),
    ]
