# Generated by Django 2.0.5 on 2019-01-10 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cebula', '0008_alarm'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buddi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.IntegerField(default=1)),
                ('role', models.IntegerField(default=1)),
                ('career', models.IntegerField(default=1)),
                ('status', models.IntegerField(default=1)),
            ],
        ),
    ]
