# Generated by Django 2.0.5 on 2019-01-11 07:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cebula', '0009_buddi'),
    ]

    operations = [
        migrations.AddField(
            model_name='buddi',
            name='name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
